# Window set shell to git bash
set -g default-shell "C:/Program Files/Git/bin/bash.exe"

# Set the splitting left & right main key.
# Change the symbol in the next next line to change splitting main key
unbind %
bind | split-window -h

# Set the splitting up & down main key.
# Change the symbol in the next next line to change splitting main key
unbind '"'
bind '-' split-window -v

# Set Prefix + r to trigger `tmux source-file ~/.tmux.conf`
unbind r
bind r source-file ~/.tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vi mode
set-window-option -g mode-keys vi

