# Split key
unbind %
bind | split-window -h
bind \ split-window -h

unbind '"'
bind '-' split-window -v
bind '_' split-window -v

# Set Prefix + r to reload the config.
unbind r
bind r source-file ~/.tmux.conf

# Prefix + m to toggle zoom in/out on the current pane
unbind m
bind m resize-pane -Z

# Vi mode
set-window-option -g mode-keys vi

# Prefix + Space to enter copy mode
unbind Space
bind Space copy-mode

# Set vi mode for copy mode key bindings (recommended for vim users)
setw -g mode-keys vi

# vim-like selection key bindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# H / L: start / end of line in copy mode
bind -T copy-mode-vi H send-keys -X start-of-line
bind -T copy-mode-vi L send-keys -X end-of-line

# renumber windows when a window is closed
set -g renumber-windows on

set -g history-limit 50000

# statusbar
set -g status-position bottom
set -g status-justify center

set -g window-status-current-format "#{window_index}:#{window_name}"
set -g window-status-current-style bg=brightblue,fg=white

set -g status-right '%Y-%m-%d %H:%M '
