# https://dev.to/brandonwallace/how-to-use-vim-mode-on-the-command-line-in-bash-fnn
set -o vi

alias gs='git status'
alias cd='z'
alias ll='ls -l'
alias la='ls --almost-all'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f ~/.oh-my-bashrc ] && source ~/.oh-my-bashrc

eval "$(zoxide init bash)"

export PATH="/c/Users/jesse/scoop/shims:$PATH"
export PATH="/c/Users/jesse/scoop/apps/maven/current/bin:$PATH"
